//! Atomic, invertible edits.

use crate::position::{Position, Range};
use crate::{CoreError, Result};

/// A single replacement of `range` with `text`.
///
/// Insert, delete and replace are all the same operation with one side empty,
/// which keeps the undo machinery down to a single case.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Change {
    /// The region to replace, in pre-edit coordinates.
    pub range: Range,
    /// The replacement text.
    pub text: String,
}

impl Change {
    /// Inserts `text` at `pos`.
    pub fn insert(pos: Position, text: String) -> Self {
        Self {
            range: Range::empty(pos),
            text,
        }
    }

    /// Deletes `range`.
    pub fn delete(range: Range) -> Self {
        Self {
            range,
            text: String::new(),
        }
    }

    /// Replaces `range` with `text`.
    pub fn replace(range: Range, text: String) -> Self {
        Self { range, text }
    }

    /// Whether this change removes nothing and inserts nothing.
    pub fn is_noop(&self) -> bool {
        self.range.is_empty() && self.text.is_empty()
    }
}

/// A set of non-overlapping changes applied as one undo step.
///
/// Multi-cursor typing produces one transaction with N changes, so a single
/// undo reverts all carets together — the behaviour users expect from VS Code.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Transaction {
    changes: Vec<Change>,
}

impl Transaction {
    /// Builds a transaction, sorting the changes and rejecting overlaps.
    ///
    /// Overlapping changes have no well-defined result, and silently merging
    /// them would corrupt the inverse, so they are an error rather than a
    /// best-effort fixup.
    pub fn new(mut changes: Vec<Change>) -> Result<Self> {
        for change in &changes {
            if change.range.start > change.range.end {
                return Err(CoreError::InvalidRange {
                    start: change.range.start,
                    end: change.range.end,
                });
            }
        }
        changes.sort_by_key(|c| (c.range.start, c.range.end));
        for pair in changes.windows(2) {
            let (a, b) = (&pair[0], &pair[1]);
            // Two carets at the same empty position are legitimate (they insert
            // in sequence); anything that actually overlaps text is not.
            let overlaps = if a.range.is_empty() && b.range.is_empty() {
                false
            } else {
                b.range.start < a.range.end
            };
            if overlaps {
                return Err(CoreError::InvalidRange {
                    start: b.range.start,
                    end: a.range.end,
                });
            }
        }
        Ok(Self { changes })
    }

    /// Builds a transaction from a single change.
    pub fn single(change: Change) -> Self {
        Self {
            changes: vec![change],
        }
    }

    /// Builds a transaction without validating. Used for inverses, which are
    /// generated by [`crate::Buffer::apply`] and are correct by construction.
    pub(crate) fn from_changes_unchecked(changes: Vec<Change>) -> Self {
        Self { changes }
    }

    /// The changes, sorted by start position.
    pub fn changes(&self) -> &[Change] {
        &self.changes
    }

    /// Whether the transaction would alter nothing.
    pub fn is_empty(&self) -> bool {
        self.changes.is_empty() || self.changes.iter().all(Change::is_noop)
    }

    /// Number of changes.
    pub fn len(&self) -> usize {
        self.changes.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn r(sl: u32, sc: u32, el: u32, ec: u32) -> Range {
        Range::new(Position::new(sl, sc), Position::new(el, ec))
    }

    #[test]
    fn changes_are_sorted_on_construction() {
        let tx = Transaction::new(vec![
            Change::insert(Position::new(3, 0), "c".into()),
            Change::insert(Position::new(1, 0), "a".into()),
            Change::insert(Position::new(2, 0), "b".into()),
        ])
        .unwrap();
        let texts: Vec<_> = tx.changes().iter().map(|c| c.text.as_str()).collect();
        assert_eq!(texts, ["a", "b", "c"]);
    }

    #[test]
    fn overlapping_changes_are_rejected() {
        let err = Transaction::new(vec![
            Change::delete(r(0, 0, 0, 5)),
            Change::delete(r(0, 3, 0, 8)),
        ])
        .unwrap_err();
        assert!(matches!(err, CoreError::InvalidRange { .. }));
    }

    #[test]
    fn adjacent_changes_are_allowed() {
        assert!(Transaction::new(vec![
            Change::delete(r(0, 0, 0, 3)),
            Change::delete(r(0, 3, 0, 6)),
        ])
        .is_ok());
    }

    #[test]
    fn two_carets_at_the_same_point_are_allowed() {
        assert!(Transaction::new(vec![
            Change::insert(Position::new(0, 2), "a".into()),
            Change::insert(Position::new(0, 2), "b".into()),
        ])
        .is_ok());
    }

    #[test]
    fn reversed_range_is_rejected() {
        let err = Transaction::new(vec![Change::delete(r(1, 0, 0, 0))]).unwrap_err();
        assert!(matches!(err, CoreError::InvalidRange { .. }));
    }

    #[test]
    fn empty_transaction_is_detected() {
        assert!(Transaction::default().is_empty());
        assert!(Transaction::single(Change::insert(Position::ZERO, String::new())).is_empty());
        assert!(!Transaction::single(Change::insert(Position::ZERO, "x".into())).is_empty());
    }
}
